/**
 * Usage Examples for SVG Extraction Utilities
 *
 * Demonstrates how to use SVG extraction in Dashboard PDF export
 */

import {
  extractRechartsChart,
  inlineAllComputedStyles,
  fixRechartsGradients,
  svgToDataURL,
  svgToDataURLAsync,
  extractChartAsDataURL
} from './svgExtractor';
import type { SvgExtractionResult } from './types';
import jsPDF from 'jspdf';

/**
 * Example 1: Basic SVG extraction from Recharts chart
 */
export async function basicChartExtraction() {
  // Extract SVG from container (e.g., Revenue chart)
  const svg = extractRechartsChart('revenue-chart-container');

  if (!svg) {
    console.error('Chart SVG not found');
    return null;
  }

  // Inline all computed styles for portability
  inlineAllComputedStyles(svg);

  // Fix gradient IDs to avoid conflicts
  fixRechartsGradients(svg);

  // Convert to data URL (PNG format)
  const dataUrl = svgToDataURL(svg, {
    scale: 2, // High DPI
    backgroundColor: '#ffffff'
  });

  return dataUrl;
}

/**
 * Example 2: Async extraction with error handling
 */
export async function asyncChartExtraction(chartId: string): Promise<string | null> {
  try {
    const svg = extractRechartsChart(chartId);

    if (!svg) {
      throw new Error(`Chart not found: ${chartId}`);
    }

    // Process SVG
    inlineAllComputedStyles(svg);
    fixRechartsGradients(svg);

    // Async conversion for guaranteed rasterization
    const dataUrl = await svgToDataURLAsync(svg, {
      scale: 3, // Extra high quality
      width: 1200, // Custom dimensions
      height: 600,
      outputFormat: 'png'
    });

    return dataUrl;

  } catch (error) {
    console.error('Chart extraction failed:', error);
    return null;
  }
}

/**
 * Example 3: Complete extraction pipeline (recommended)
 */
export async function completeChartExtraction(
  chartId: string
): Promise<SvgExtractionResult> {
  // All-in-one extraction with automatic error handling
  const result = await extractChartAsDataURL(chartId, {
    scale: 2,
    backgroundColor: '#ffffff',
    inlineStyles: true,
    fixGradients: true,
    outputFormat: 'png'
  });

  if (!result.success) {
    console.error('Extraction failed:', result.error);
  }

  return result;
}

/**
 * Example 4: Multiple charts for PDF
 */
export async function extractMultipleCharts() {
  const chartIds = [
    'revenue-chart-container',
    'bookings-chart-container',
    'comparison-chart-container'
  ];

  const results = await Promise.all(
    chartIds.map(id => extractChartAsDataURL(id, { scale: 2 }))
  );

  // Filter successful extractions
  const successfulCharts = results.filter(r => r.success);

  console.log(`Extracted ${successfulCharts.length}/${chartIds.length} charts`);

  return successfulCharts;
}

/**
 * Example 5: Add extracted chart to PDF
 */
export async function addChartToPDF(
  pdf: jsPDF,
  chartId: string,
  x: number,
  y: number,
  width: number
) {
  const result = await extractChartAsDataURL(chartId);

  if (!result.success) {
    console.error('Chart extraction failed:', result.error);
    return false;
  }

  // Calculate height maintaining aspect ratio
  const aspectRatio = result.height / result.width;
  const height = width * aspectRatio;

  // Add to PDF
  pdf.addImage(result.dataUrl, 'PNG', x, y, width, height);

  return true;
}

/**
 * Example 6: Dashboard export with multiple charts
 */
export async function exportDashboardToPDF(
  user: { name: string; email: string },
  scenarioName: string
) {
  const pdf = new jsPDF('p', 'mm', 'a4');

  // A4 dimensions
  const pageWidth = 210;
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;

  let yPosition = 20;

  // Add title
  pdf.setFontSize(20);
  pdf.text('JAUNTY Revenue Forecast Report', margin, yPosition);
  yPosition += 10;

  pdf.setFontSize(12);
  pdf.text(`Scenario: ${scenarioName}`, margin, yPosition);
  yPosition += 5;
  pdf.text(`Generated by: ${user.name}`, margin, yPosition);
  yPosition += 15;

  // Extract and add main forecast chart
  const forecastResult = await extractChartAsDataURL('revenue-chart-container', {
    scale: 2,
    backgroundColor: '#ffffff'
  });

  if (forecastResult.success) {
    const chartAspectRatio = forecastResult.height / forecastResult.width;
    const chartHeight = contentWidth * chartAspectRatio;

    pdf.addImage(
      forecastResult.dataUrl,
      'PNG',
      margin,
      yPosition,
      contentWidth,
      chartHeight
    );
    yPosition += chartHeight + 10;
  }

  // Add bookings chart if space available
  if (yPosition < 250) {
    const bookingsResult = await extractChartAsDataURL('bookings-chart-container', {
      scale: 2
    });

    if (bookingsResult.success) {
      const chartAspectRatio = bookingsResult.height / bookingsResult.width;
      const chartHeight = contentWidth * chartAspectRatio;

      if (yPosition + chartHeight > 280) {
        pdf.addPage();
        yPosition = 20;
      }

      pdf.addImage(
        bookingsResult.dataUrl,
        'PNG',
        margin,
        yPosition,
        contentWidth,
        chartHeight
      );
    }
  }

  // Save PDF
  pdf.save(`jaunty-forecast-${scenarioName}-${Date.now()}.pdf`);
}

/**
 * Example 7: SVG format export (smaller file size)
 */
export async function extractChartAsSVG(chartId: string): Promise<string | null> {
  const result = await extractChartAsDataURL(chartId, {
    outputFormat: 'svg', // Keep as vector
    inlineStyles: true,
    fixGradients: true
  });

  if (result.success) {
    return result.dataUrl;
  }

  return null;
}

/**
 * Example 8: Custom styling before extraction
 */
export async function extractWithCustomStyling(chartId: string) {
  const svg = extractRechartsChart(chartId);

  if (!svg) {
    return null;
  }

  // Apply custom styles before extraction
  svg.style.backgroundColor = '#f8fafc';

  // Find all text elements and adjust font
  const textElements = svg.querySelectorAll('text');
  textElements.forEach(text => {
    text.style.fontFamily = 'Arial, sans-serif';
    text.style.fontSize = '12px';
  });

  // Inline computed styles
  inlineAllComputedStyles(svg);
  fixRechartsGradients(svg);

  // Convert to data URL
  const dataUrl = await svgToDataURLAsync(svg, {
    scale: 2,
    backgroundColor: '#f8fafc'
  });

  return dataUrl;
}

/**
 * Example 9: Integration with existing pdfComposer
 */
export async function integrateWithPDFComposer() {
  const { composePDF } = await import('./pdfComposer');

  // Extract chart
  const chartResult = await extractChartAsDataURL('revenue-chart-container');

  if (!chartResult.success) {
    throw new Error('Chart extraction failed');
  }

  // Create sections for PDF composer
  const sections = [
    {
      type: 'cover' as const,
      title: 'Executive Summary',
      data: { /* forecast data */ }
    },
    {
      type: 'chart' as const,
      title: 'Revenue Forecast Visualization',
      svgDataUrl: chartResult.dataUrl
    }
  ];

  // Compose PDF
  const pdf = await composePDF(sections, {
    filename: 'jaunty-forecast',
    user: {
      name: 'John Doe',
      email: 'john@example.com',
      role: 'admin'
    }
  });

  return pdf;
}

/**
 * Example 10: Fallback handling
 */
export async function extractWithFallback(chartId: string): Promise<string> {
  // Try SVG extraction first
  const result = await extractChartAsDataURL(chartId, {
    outputFormat: 'png',
    scale: 2
  });

  if (result.success) {
    return result.dataUrl;
  }

  // Fallback: try lower quality
  const fallbackResult = await extractChartAsDataURL(chartId, {
    outputFormat: 'svg',
    scale: 1
  });

  if (fallbackResult.success) {
    console.warn('Using fallback SVG extraction');
    return fallbackResult.dataUrl;
  }

  // Ultimate fallback: use html2canvas
  const container = document.getElementById(chartId);
  if (container) {
    const html2canvas = (await import('html2canvas')).default;
    const canvas = await html2canvas(container, {
      scale: 1,
      logging: false
    });
    return canvas.toDataURL('image/png');
  }

  throw new Error('All extraction methods failed');
}
